### ISSUE TITLE
package makerscanner for debian/ubuntu

### ISSUE THREAD

**Issue by robinpaulson** [andybarry/makerscanner#9]
Perhaps on launchpad?

Cheers

**Comment by robinpaulson** [comment]
I decided to package makerscanner myself and will upload to launchpad. I see there is no manpage, would you be able to provide that for the package? Or at least a list of runtime options so I can put one together?

Thanks

**Comment by andybarry** [comment]
It's been a while, but I'm not sure it has any runtime command line flags.
All of the stuff is setable in the GUI.

For a man page, the best thing to do is probably to copy the text and links
from here: http://www.makerscanner.com/

**Comment by robinpaulson** [comment]
Cheers, will do.

**Comment by andybarry** [comment]
Awesome, thanks!
